config/routes.rb
Rails.application.routes.draw do
  resources :order_details
  get 'sign_up/index'=> 'sign_up/index', :as => 'sign_up'
  get 'login/index'=> 'login/index', :as => 'login'
  get 'new_item/index' => 'new_item/index', :as => 'new_item'
  get 'sale_item/index' => 'sale_item/index', :as => 'sale_item'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'product_search/index'=> 'product_search/index', :as => 'search_page'
  resources :provinces
  resources :users
  resources :orders
  resources :categories
  resources :products

  root to: "products#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :Products
    has_one_attached :image
    validates :name, :description, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :Category
    validates :name, :brand,:manufacturer, :source, :brand, :price, :isSale, :image, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :Users
    validates :name, :GST, :PST, :HST, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :Province
    validates :first_name, :last_name, :password, :address, presence: true
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    session[:login] = 0


    if session[:signup] == 0
      if params[:password].blank? || params[:first_name].blank? || params[:last_name].blank? || params[:address].blank? || params[:province].blank?
        redirect_to(sign_up_path, alert: 'Empty field!') and return
      else
        session[:signup] = 1
        User.create(first_name: params[:first_name], last_name: params[:last_name], password: params[:password], address:params[:address], Province_id: params[:province])
        redirect_to(login_path, alert: 'Invalid User!') and return
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :password, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/new_item_helper.rb
module NewItemHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/sale_item_helper.rb
module SaleItemHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Electronics Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav  class="has-background-grey-light">
  <div class="level">
    <ul >
      <li class="subtitle is-6"><%= link_to "Products's", products_path%></li>
      <li class="subtitle is-6"><%= link_to "Categories", categories_path%></li>
      <%# <li class="subtitle is-6"><%= link_to "About Us", "http://127.0.0.1:3000/about/index"%>
    </ul>

      <%= form_tag(search_page_path, :method => "get",
        class: 'navbar-form navbar-left') do %>
      <div class="input-group">

        <%= select_tag 'category', options_from_collection_for_select(Category.all, :id,:name), include_blank: "Select Category", class: "select is-info" %>

        <%= search_field_tag :search, params[:search], placeholder: "Search", class: "input is-info" %>
        <div class="input-group-btn">
          <%= button_tag "Search", :class => 'button is-info',:name => nil%>
        </div>
        <div>
        <div>
      </div>
    <% end %>
    <br>
    <%# changepath %>
    <%= form_tag(search_page_path, :method => "get",
        class: 'navbar-form navbar-right') do %>
        <div class="input-group-btn">
          <%= button_tag "Check Out", :class => 'button is-info',:name => nil%>
        </div>
    <% end %>
    <br>
    <p>
      <%= form_tag(sale_item_path, :method => "get",
          class: 'navbar-form navbar-left') do %>
          <%= button_tag "Items On Sale", :class => 'button is-info',:name => nil%>
      <% end %> 
      <%= form_tag(new_item_path, :method => "get",
          class: 'navbar-form navbar-left') do %>
          <%= button_tag "Items just added", :class => 'button is-info',:name => nil%>
      <% end %> 
    </p>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>